{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "invite",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "invite-3.6.200.23.aar",
          "url": "invite-3.6.200.23.aar",
          "size": 805201,
          "sha512": "f8c3bbafc842351b8a3534a399d3d03c309d6235014297e6464389e1c1e4468b51cb39e64e2a89dd4b32bf914d4d370a8470d9dfe59d12973c11d1c4587a603e",
          "sha256": "3b123efcaee866fec39345a9bc531ff49c989640f20e5034e999fad3fb0edd53",
          "sha1": "d95d0f7c015f8799b2ae785c025c9734ab3a8e9c",
          "md5": "9fda92fcb7826c1f0c9c217357838205"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "invite-3.6.200.23.aar",
          "url": "invite-3.6.200.23.aar",
          "size": 805201,
          "sha512": "f8c3bbafc842351b8a3534a399d3d03c309d6235014297e6464389e1c1e4468b51cb39e64e2a89dd4b32bf914d4d370a8470d9dfe59d12973c11d1c4587a603e",
          "sha256": "3b123efcaee866fec39345a9bc531ff49c989640f20e5034e999fad3fb0edd53",
          "sha1": "d95d0f7c015f8799b2ae785c025c9734ab3a8e9c",
          "md5": "9fda92fcb7826c1f0c9c217357838205"
        }
      ]
    }
  ]
}
