{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet.modules",
    "module": "invite",
    "version": "3.12.201.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "invite-3.12.201.9.aar",
          "url": "invite-3.12.201.9.aar",
          "size": 1396687,
          "sha512": "1692750f2f2f93d7dd0ca26298dbffd787aaac731dc1ac98ee66e53978a9f93ee724e1eaa5196aa85eeb371591390c233f7da5cd8ab4b8fde0407ace99ebb599",
          "sha256": "8c9fe41ce94b5373b814554d0c5d25538f3aed9f65f9cfbd28d2b2a8896a3ddd",
          "sha1": "63a51cd52ea12e9571cd42f21d3ac1b222c1c189",
          "md5": "44d3f131a8620ebb66f227d76e4f04f0"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webcore",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "professional",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "invite-3.12.201.9.aar",
          "url": "invite-3.12.201.9.aar",
          "size": 1396687,
          "sha512": "1692750f2f2f93d7dd0ca26298dbffd787aaac731dc1ac98ee66e53978a9f93ee724e1eaa5196aa85eeb371591390c233f7da5cd8ab4b8fde0407ace99ebb599",
          "sha256": "8c9fe41ce94b5373b814554d0c5d25538f3aed9f65f9cfbd28d2b2a8896a3ddd",
          "sha1": "63a51cd52ea12e9571cd42f21d3ac1b222c1c189",
          "md5": "44d3f131a8620ebb66f227d76e4f04f0"
        }
      ]
    }
  ]
}
