{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "tkvwrapper",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkvwrapper-3.6.200.23.aar",
          "url": "tkvwrapper-3.6.200.23.aar",
          "size": 52927,
          "sha512": "15933d1c44625712e95e53c4c3b39a2dc90820b21b01f879eb95b18c1d680a763c3302377ca5bc44bcbff55a429e72561102bc21d269f7144df3426b2f5d1f81",
          "sha256": "9b8d9e26459affdffd8e0a4a61509ca4f0418ad112d6b2d2d58b11596d49445f",
          "sha1": "c32e3d2b996abbbc38f5ede18e282b3aee96055a",
          "md5": "d933a23955febb5b049e3a483e16bd24"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "tkvwrapper-3.6.200.23.aar",
          "url": "tkvwrapper-3.6.200.23.aar",
          "size": 52927,
          "sha512": "15933d1c44625712e95e53c4c3b39a2dc90820b21b01f879eb95b18c1d680a763c3302377ca5bc44bcbff55a429e72561102bc21d269f7144df3426b2f5d1f81",
          "sha256": "9b8d9e26459affdffd8e0a4a61509ca4f0418ad112d6b2d2d58b11596d49445f",
          "sha1": "c32e3d2b996abbbc38f5ede18e282b3aee96055a",
          "md5": "d933a23955febb5b049e3a483e16bd24"
        }
      ]
    }
  ]
}
