{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "base-jni",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "base-jni-3.6.200.23.aar",
          "url": "base-jni-3.6.200.23.aar",
          "size": 42486,
          "sha512": "a5b56b1dbe2aaf0f98329961e55eb308d81016772c87adcffa3d9544713880635bcea904c195a39daed4043a64991b4b8e9764f97e03293dbb7fd7ebbb24de10",
          "sha256": "02d67a177880d89aecf127a1574c307488ec453d66fa20b6c7721b3aab62eef0",
          "sha1": "311229d9dcb7238019927c6481d3ba5a479e1eb9",
          "md5": "bc5a9485490e964ff80759178bf9f599"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "base-jni-3.6.200.23.aar",
          "url": "base-jni-3.6.200.23.aar",
          "size": 42486,
          "sha512": "a5b56b1dbe2aaf0f98329961e55eb308d81016772c87adcffa3d9544713880635bcea904c195a39daed4043a64991b4b8e9764f97e03293dbb7fd7ebbb24de10",
          "sha256": "02d67a177880d89aecf127a1574c307488ec453d66fa20b6c7721b3aab62eef0",
          "sha1": "311229d9dcb7238019927c6481d3ba5a479e1eb9",
          "md5": "bc5a9485490e964ff80759178bf9f599"
        }
      ]
    }
  ]
}
