{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "webview",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "webview-3.6.200.23.aar",
          "url": "webview-3.6.200.23.aar",
          "size": 505158,
          "sha512": "275a7a85da0cadd96da70cbf84a8dec6d54de645f499ee2f3c9d4448cec15ccce2bcf3a7ab1796861a55157085d382fe686a29aef3823843ccf105d091d5de00",
          "sha256": "6e36b08d437221415cb904b32ac0a68cf67b6598d2260902bc7fa9afbf5f0344",
          "sha1": "5042b2ce31ac6b14c9481f9b6b380fb298bc6b63",
          "md5": "97aa220e0377d2ade13309edf6f3521f"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview-3.6.200.23.aar",
          "url": "webview-3.6.200.23.aar",
          "size": 505158,
          "sha512": "275a7a85da0cadd96da70cbf84a8dec6d54de645f499ee2f3c9d4448cec15ccce2bcf3a7ab1796861a55157085d382fe686a29aef3823843ccf105d091d5de00",
          "sha256": "6e36b08d437221415cb904b32ac0a68cf67b6598d2260902bc7fa9afbf5f0344",
          "sha1": "5042b2ce31ac6b14c9481f9b6b380fb298bc6b63",
          "md5": "97aa220e0377d2ade13309edf6f3521f"
        }
      ]
    }
  ]
}
