{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "reddot",
    "version": "3.6.203.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "reddot-3.6.203.71.aar",
          "url": "reddot-3.6.203.71.aar",
          "size": 50180,
          "sha512": "b9ee533802f279db010b7e1764e58cd7d33c07501d79c3520807dfaa8a11c8df01a5ba0f26b7ef8650efa72dc66cec66fb66127defc12b63ab5ded9af2f414f4",
          "sha256": "a7ea9a2c343f3ef94579851d9598034f2a5b36b7dd02aa3430f04e5de0040522",
          "sha1": "db93a5b72135691f881d7429137b488b0e0bb12a",
          "md5": "bbe16c11c01f85416ae12fcee4497df4"
        }
      ]
    },
    {
      "name": "productReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.203.71"
          }
        }
      ],
      "files": [
        {
          "name": "reddot-3.6.203.71.aar",
          "url": "reddot-3.6.203.71.aar",
          "size": 50180,
          "sha512": "b9ee533802f279db010b7e1764e58cd7d33c07501d79c3520807dfaa8a11c8df01a5ba0f26b7ef8650efa72dc66cec66fb66127defc12b63ab5ded9af2f414f4",
          "sha256": "a7ea9a2c343f3ef94579851d9598034f2a5b36b7dd02aa3430f04e5de0040522",
          "sha1": "db93a5b72135691f881d7429137b488b0e0bb12a",
          "md5": "bbe16c11c01f85416ae12fcee4497df4"
        }
      ]
    }
  ]
}
