{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "tm-bugly-sdk",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "tm-bugly-sdk-3.6.200.23.aar",
          "url": "tm-bugly-sdk-3.6.200.23.aar",
          "size": 57085,
          "sha512": "87955a74da04d08c3433595c51e485266c855ae5be7a49bdd93667dcf5027dfb5c00a37f0cf150ab357dbcdacc6e2e85738bef8deba3da02bce9095ade9c8883",
          "sha256": "a7e17b7bdd7af3ea7fbcb83dc182a9fc763f3b1590a319b972a61805d64277db",
          "sha1": "969ddce68e8052da0b160f856048b707c5caa8e5",
          "md5": "c565e680d06b7336b45a8375d037565e"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport",
          "version": {
            "requires": "4.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "tm-bugly-sdk-3.6.200.23.aar",
          "url": "tm-bugly-sdk-3.6.200.23.aar",
          "size": 57085,
          "sha512": "87955a74da04d08c3433595c51e485266c855ae5be7a49bdd93667dcf5027dfb5c00a37f0cf150ab357dbcdacc6e2e85738bef8deba3da02bce9095ade9c8883",
          "sha256": "a7e17b7bdd7af3ea7fbcb83dc182a9fc763f3b1590a319b972a61805d64277db",
          "sha1": "969ddce68e8052da0b160f856048b707c5caa8e5",
          "md5": "c565e680d06b7336b45a8375d037565e"
        }
      ]
    }
  ]
}
