{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "tm-bugly-sdk",
    "version": "3.12.401.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet",
          "version": {
            "requires": "3.12.401.11"
          }
        }
      ],
      "files": [
        {
          "name": "tm-bugly-sdk-3.12.401.11.aar",
          "url": "tm-bugly-sdk-3.12.401.11.aar",
          "size": 63179,
          "sha512": "91d79e714c5b5a2ad9498f8f4f2fe0ce9767931a2293e07d5cad46769e99039231175dbbbca9b6798ee8494ae42b61997fda4541644bdde874f5040beb8809b2",
          "sha256": "df31737b0d8f54c1dbc9c8c9ea3d1ad9ae40aaf5f7ff388d2ebe54ebb40367cd",
          "sha1": "77f61e9176a8300a10d46ff5899048a5ff55054f",
          "md5": "a8ee07c8cc4eeabc840f3610d3a19fdb"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport",
          "version": {
            "requires": "4.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "tm-bugly-sdk-3.12.401.11.aar",
          "url": "tm-bugly-sdk-3.12.401.11.aar",
          "size": 63179,
          "sha512": "91d79e714c5b5a2ad9498f8f4f2fe0ce9767931a2293e07d5cad46769e99039231175dbbbca9b6798ee8494ae42b61997fda4541644bdde874f5040beb8809b2",
          "sha256": "df31737b0d8f54c1dbc9c8c9ea3d1ad9ae40aaf5f7ff388d2ebe54ebb40367cd",
          "sha1": "77f61e9176a8300a10d46ff5899048a5ff55054f",
          "md5": "a8ee07c8cc4eeabc840f3610d3a19fdb"
        }
      ]
    }
  ]
}
