{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "chat",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "chat-3.6.200.23.aar",
          "url": "chat-3.6.200.23.aar",
          "size": 1489759,
          "sha512": "786a97c53c073455b8ef3071cfe7911ededea1d4add7b32eb279741c96f6ebcfbc883aec66986b4fdc0fd37dec9e32aaf4cd14f219a31093d80f45def93aa379",
          "sha256": "b3dd5461c7f24f0e01f73aa3f05578628735d1b9a7e2ec447f5b19a6b8049d5b",
          "sha1": "454948f2d4ca540a7dc8a2065c267a16be7baf18",
          "md5": "78394aea538ad65565dd3ee50712ceeb"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.45"
          }
        }
      ],
      "files": [
        {
          "name": "chat-3.6.200.23.aar",
          "url": "chat-3.6.200.23.aar",
          "size": 1489759,
          "sha512": "786a97c53c073455b8ef3071cfe7911ededea1d4add7b32eb279741c96f6ebcfbc883aec66986b4fdc0fd37dec9e32aaf4cd14f219a31093d80f45def93aa379",
          "sha256": "b3dd5461c7f24f0e01f73aa3f05578628735d1b9a7e2ec447f5b19a6b8049d5b",
          "sha1": "454948f2d4ca540a7dc8a2065c267a16be7baf18",
          "md5": "78394aea538ad65565dd3ee50712ceeb"
        }
      ]
    }
  ]
}
