{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "misc",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "videoplayer",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "misc-3.6.200.23.aar",
          "url": "misc-3.6.200.23.aar",
          "size": 212246,
          "sha512": "c605672b987bba7dc6b53b701c8eed5222b72e5d63f2f68411dcb2ce0829d362730ffa4325247c6dbe04aa6dbe3c148549c844574b6dc6a530178df4647046d9",
          "sha256": "d29ad70558f9c32bdd9279b1271d41a02ede4b6fb332125934a3a2a7b1a0a66a",
          "sha1": "9eba978d4868c2df5d85d5bc0447bd51fbd2dd3f",
          "md5": "fc6c345132d59c9ee49f227d8107bcf7"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "videoplayer",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "misc-3.6.200.23.aar",
          "url": "misc-3.6.200.23.aar",
          "size": 212246,
          "sha512": "c605672b987bba7dc6b53b701c8eed5222b72e5d63f2f68411dcb2ce0829d362730ffa4325247c6dbe04aa6dbe3c148549c844574b6dc6a530178df4647046d9",
          "sha256": "d29ad70558f9c32bdd9279b1271d41a02ede4b6fb332125934a3a2a7b1a0a66a",
          "sha1": "9eba978d4868c2df5d85d5bc0447bd51fbd2dd3f",
          "md5": "fc6c345132d59c9ee49f227d8107bcf7"
        }
      ]
    }
  ]
}
