{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "login",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "login-3.6.200.23.aar",
          "url": "login-3.6.200.23.aar",
          "size": 956173,
          "sha512": "4551464eadc7c0d74b287651c2f470cae8a8faaaa8f13246085a043d212b1f219e71cc630190f3e2360cabc59450b8d8e4973f757b241d6e6f0119ffbe5bd916",
          "sha256": "6f0a0bc95153ac95e427de84439667a7d9e8261514343fd5a87e30dd02241c65",
          "sha1": "31d23072b0657e93befbcbc246818bbd91692259",
          "md5": "5400baa09223549bfb6c66d8714851c5"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "login-3.6.200.23.aar",
          "url": "login-3.6.200.23.aar",
          "size": 956173,
          "sha512": "4551464eadc7c0d74b287651c2f470cae8a8faaaa8f13246085a043d212b1f219e71cc630190f3e2360cabc59450b8d8e4973f757b241d6e6f0119ffbe5bd916",
          "sha256": "6f0a0bc95153ac95e427de84439667a7d9e8261514343fd5a87e30dd02241c65",
          "sha1": "31d23072b0657e93befbcbc246818bbd91692259",
          "md5": "5400baa09223549bfb6c66d8714851c5"
        }
      ]
    }
  ]
}
