{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "wemeet",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-3.6.200.23.aar",
          "url": "wemeet-3.6.200.23.aar",
          "size": 16815859,
          "sha512": "e0e0bbaeed44002586cae2d980e3bae4c6bd66e763a4f2dc2c8154b8018be335baaea229ebfab0020f71f5709f388c16645434af0eb9d57f8cfe5cef5a2a2d6c",
          "sha256": "9b5e3de7ba35d3aceb9c29b1141d18dae68a1b6db95431eb228ee224a9cd7d47",
          "sha1": "4577f507f7d6ab8bd3eaf71fd95ae9882b21a27a",
          "md5": "b90428e865092b279809b8f6f8e1e446"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "imsdk",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "xcast",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-loader",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "play-core-library",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.tencent.liteav",
          "module": "LiteAVSDK_Player",
          "version": {
            "requires": "9.3.10769"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "qbar",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.31"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.leon.channel",
          "module": "helper",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-3.6.200.23.aar",
          "url": "wemeet-3.6.200.23.aar",
          "size": 16815859,
          "sha512": "e0e0bbaeed44002586cae2d980e3bae4c6bd66e763a4f2dc2c8154b8018be335baaea229ebfab0020f71f5709f388c16645434af0eb9d57f8cfe5cef5a2a2d6c",
          "sha256": "9b5e3de7ba35d3aceb9c29b1141d18dae68a1b6db95431eb228ee224a9cd7d47",
          "sha1": "4577f507f7d6ab8bd3eaf71fd95ae9882b21a27a",
          "md5": "b90428e865092b279809b8f6f8e1e446"
        }
      ]
    }
  ]
}
