{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "webview",
    "version": "3.6.203.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "webview-3.6.203.71.aar",
          "url": "webview-3.6.203.71.aar",
          "size": 508741,
          "sha512": "7067b3c7787edf938577aeb95908835b51b7efe4666695255dd44b051636dc5cd56474dc384061f05b4d047e2c4154b074ddba4775172cb5d6972fc9ac711328",
          "sha256": "9f4751a0bfb9e0c3d0ac1709a130d3f8a4634d00d9c9a0b2f8fe89e665ed4f4c",
          "sha1": "48590cf50695c4b9060866f1802a34082e173f41",
          "md5": "cece62ffd7dbec44bc70cb503c2f4e13"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview-3.6.203.71.aar",
          "url": "webview-3.6.203.71.aar",
          "size": 508741,
          "sha512": "7067b3c7787edf938577aeb95908835b51b7efe4666695255dd44b051636dc5cd56474dc384061f05b4d047e2c4154b074ddba4775172cb5d6972fc9ac711328",
          "sha256": "9f4751a0bfb9e0c3d0ac1709a130d3f8a4634d00d9c9a0b2f8fe89e665ed4f4c",
          "sha1": "48590cf50695c4b9060866f1802a34082e173f41",
          "md5": "cece62ffd7dbec44bc70cb503c2f4e13"
        }
      ]
    }
  ]
}
