{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet.modules",
    "module": "quick_meeting",
    "version": "3.12.201.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "quick_meeting-3.12.201.9.aar",
          "url": "quick_meeting-3.12.201.9.aar",
          "size": 203539,
          "sha512": "bdd3b6d0029f2cb30105bd82ed69bac67eb0a72aa4e57a36d118321c99384bb1f3c0a103396ca594a184a2eb6707eaa83cacc8edf9c251dc29d33cd55f828dd6",
          "sha256": "2ca1f42ac18d324c7b6e019822580b3ff72f745142db4a7cf816e4f15651bc4a",
          "sha1": "1f6138aaf0a3aaf0a36ee41fa36a3543f58bac6a",
          "md5": "9e7aae52d5034020e601a99e3ea97a78"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webcore",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "professional",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "quick_meeting-3.12.201.9.aar",
          "url": "quick_meeting-3.12.201.9.aar",
          "size": 203539,
          "sha512": "bdd3b6d0029f2cb30105bd82ed69bac67eb0a72aa4e57a36d118321c99384bb1f3c0a103396ca594a184a2eb6707eaa83cacc8edf9c251dc29d33cd55f828dd6",
          "sha256": "2ca1f42ac18d324c7b6e019822580b3ff72f745142db4a7cf816e4f15651bc4a",
          "sha1": "1f6138aaf0a3aaf0a36ee41fa36a3543f58bac6a",
          "md5": "9e7aae52d5034020e601a99e3ea97a78"
        }
      ]
    }
  ]
}
