{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "module-core",
    "version": "3.6.203.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "xcast",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "auth",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "uikit",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "lottie",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "push",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "tbssdk-dynamic",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.yqritc",
          "module": "recyclerview-flexibledivider",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "module-core-3.6.203.71.aar",
          "url": "module-core-3.6.203.71.aar",
          "size": 3268283,
          "sha512": "dc97e3e4c94874e71d2356c47a457b6de854a1d6a02797be82e5ecc4f9709882e8e07b14854d285473233285fe65e5fe27f2c0f1cf896f207cf818bfb4ed0c21",
          "sha256": "20ed2b184064c3c50dfac4eef4d726914516cf3ab1322b46e5bb3755049b2dff",
          "sha1": "61598ffa2a1c0cea4361272242b502fd7a3ef5ff",
          "md5": "306a41b6bfd16062f2b18a95ddd81ed0"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "xcast",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "auth",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "uikit",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "lottie",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "push",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "tbssdk-dynamic",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.yqritc",
          "module": "recyclerview-flexibledivider",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "captchasdk",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-loader",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.45"
          }
        },
        {
          "group": "yt-parvati.yt-parvati-wemeet",
          "module": "yt-parvati-wemeet-resource",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "yt-parvati.yt-parvati-wemeet",
          "module": "yt-parvati-wemeet-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "yt-3d-avatar.wemeet",
          "module": "yt-3d-avatar-wemeet",
          "version": {
            "requires": "v2.2.12"
          }
        },
        {
          "group": "youtu.yt-mobile-sdk",
          "module": "libYTCommon",
          "version": {
            "requires": "v2.4.4_meeting"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-core-3.6.203.71.aar",
          "url": "module-core-3.6.203.71.aar",
          "size": 3268283,
          "sha512": "dc97e3e4c94874e71d2356c47a457b6de854a1d6a02797be82e5ecc4f9709882e8e07b14854d285473233285fe65e5fe27f2c0f1cf896f207cf818bfb4ed0c21",
          "sha256": "20ed2b184064c3c50dfac4eef4d726914516cf3ab1322b46e5bb3755049b2dff",
          "sha1": "61598ffa2a1c0cea4361272242b502fd7a3ef5ff",
          "md5": "306a41b6bfd16062f2b18a95ddd81ed0"
        }
      ]
    }
  ]
}
