{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "meeting_room",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "meeting_room-3.6.200.23.aar",
          "url": "meeting_room-3.6.200.23.aar",
          "size": 313478,
          "sha512": "b1732bc10a2613697a2d487d1864023680aa102b9bb57474e90688e4e2a9404603e97903422e30f8d116e1b59fb45d9c4b6b56df80f722fc2973666eb5a0296a",
          "sha256": "339c6e4ce679ef1f145c1cc02c5cd788e29582b1d455de0d6c400d9d60c8d2cd",
          "sha1": "82e05b6c41d7c2f902ad618d18bf324e8ef01a84",
          "md5": "aa6bc18eea933bd9d141e117f6836659"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "meeting_room-3.6.200.23.aar",
          "url": "meeting_room-3.6.200.23.aar",
          "size": 313478,
          "sha512": "b1732bc10a2613697a2d487d1864023680aa102b9bb57474e90688e4e2a9404603e97903422e30f8d116e1b59fb45d9c4b6b56df80f722fc2973666eb5a0296a",
          "sha256": "339c6e4ce679ef1f145c1cc02c5cd788e29582b1d455de0d6c400d9d60c8d2cd",
          "sha1": "82e05b6c41d7c2f902ad618d18bf324e8ef01a84",
          "md5": "aa6bc18eea933bd9d141e117f6836659"
        }
      ]
    }
  ]
}
