{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet.modules",
    "module": "member",
    "version": "3.12.401.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "member-3.12.401.11.aar",
          "url": "member-3.12.401.11.aar",
          "size": 1705599,
          "sha512": "0d3137008519b2906f9ab59f8f53db0ec0cec7525a64bb1a9e657aeb71f240d0e2b5ac74c689266014991c32422e09ecf730e19b759f003037cfa8aefa070563",
          "sha256": "e6091cea05762f89d065e591b954a2835ec02b035480e31f1e7930f127960c73",
          "sha1": "0656b420d55e71c034aced3709e240f6cd3ec888",
          "md5": "390a821ff495302ada971f4c36459feb"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webcore",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "professional",
          "version": {
            "requires": "3.12.401.11"
          }
        }
      ],
      "files": [
        {
          "name": "member-3.12.401.11.aar",
          "url": "member-3.12.401.11.aar",
          "size": 1705599,
          "sha512": "0d3137008519b2906f9ab59f8f53db0ec0cec7525a64bb1a9e657aeb71f240d0e2b5ac74c689266014991c32422e09ecf730e19b759f003037cfa8aefa070563",
          "sha256": "e6091cea05762f89d065e591b954a2835ec02b035480e31f1e7930f127960c73",
          "sha1": "0656b420d55e71c034aced3709e240f6cd3ec888",
          "md5": "390a821ff495302ada971f4c36459feb"
        }
      ]
    }
  ]
}
