{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "webview",
    "version": "3.12.401.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "websdk",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "webview-3.12.401.11.aar",
          "url": "webview-3.12.401.11.aar",
          "size": 974981,
          "sha512": "e374428189b699fd1b0122e5c73dbb9ee19a5e20cf138b68d131462427681ba0a98211938e31770f0f70ae5dd9f46c904e7ee0ac242245254b001ceaf68a1155",
          "sha256": "96103ae6203d06fb2966820799e1b6c893523102b929a6a73ad80c2dcf1399d6",
          "sha1": "0d57fa2a1f89c3f148edb43d22a47384df115098",
          "md5": "797b3a6af9b9be246295db2d958e570d"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "websdk",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-loader",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.45"
          }
        },
        {
          "group": "com.tencent.liteav",
          "module": "LiteAVSDK_Player",
          "version": {
            "requires": "9.5.29040"
          }
        }
      ],
      "files": [
        {
          "name": "webview-3.12.401.11.aar",
          "url": "webview-3.12.401.11.aar",
          "size": 974981,
          "sha512": "e374428189b699fd1b0122e5c73dbb9ee19a5e20cf138b68d131462427681ba0a98211938e31770f0f70ae5dd9f46c904e7ee0ac242245254b001ceaf68a1155",
          "sha256": "96103ae6203d06fb2966820799e1b6c893523102b929a6a73ad80c2dcf1399d6",
          "sha1": "0d57fa2a1f89c3f148edb43d22a47384df115098",
          "md5": "797b3a6af9b9be246295db2d958e570d"
        }
      ]
    }
  ]
}
