{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "videoplayer",
    "version": "3.12.401.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.liteav",
          "module": "LiteAVSDK_Player",
          "version": {
            "requires": "9.5.29040"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "videoplayer-3.12.401.11.aar",
          "url": "videoplayer-3.12.401.11.aar",
          "size": 104845,
          "sha512": "116eddd0ecb678530a17cc24254ab659958e7ce5fa4c2b95026b23916fd785b379ee7e8d6935544dc5be8bea4a2a99c953d1cc42290a2dbb43db94d37207a68b",
          "sha256": "ecd464f6710c59e1c3038cad4e3c73d6d0ccc6579fd56dc0a4bf375fb5dd0532",
          "sha1": "a23cf00c9371af41688b4a3a5f622fe0a3e094d5",
          "md5": "c657a7bf634d9cbc66bbbf79c0332f9c"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.liteav",
          "module": "LiteAVSDK_Player",
          "version": {
            "requires": "9.5.29040"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "videoplayer-3.12.401.11.aar",
          "url": "videoplayer-3.12.401.11.aar",
          "size": 104845,
          "sha512": "116eddd0ecb678530a17cc24254ab659958e7ce5fa4c2b95026b23916fd785b379ee7e8d6935544dc5be8bea4a2a99c953d1cc42290a2dbb43db94d37207a68b",
          "sha256": "ecd464f6710c59e1c3038cad4e3c73d6d0ccc6579fd56dc0a4bf375fb5dd0532",
          "sha1": "a23cf00c9371af41688b4a3a5f622fe0a3e094d5",
          "md5": "c657a7bf634d9cbc66bbbf79c0332f9c"
        }
      ]
    }
  ]
}
