{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "wemeet",
    "version": "3.6.203.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-3.6.203.71.aar",
          "url": "wemeet-3.6.203.71.aar",
          "size": 16817990,
          "sha512": "cadf1b1383b9bbaef7b62e640e4ea13dfeb2591b0750eeafa76c42bd40bf14a4b5a396d5d3f6217bf5c3966cc8aa9c2651e9f2186d456212700099e80f9f498d",
          "sha256": "d54f801b5bbd334746dd9516b8fbadf8189ac160ff02c42db7dd1c53ac28c78b",
          "sha1": "1547189ab1eb4775523b9375c75d8f96f855d29a",
          "md5": "41539d18e3628202920a334e424ab98c"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "imsdk",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "xcast",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-loader",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "play-core-library",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.tencent.liteav",
          "module": "LiteAVSDK_Player",
          "version": {
            "requires": "9.3.10769"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "qbar",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.45"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.leon.channel",
          "module": "helper",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.203.71"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-3.6.203.71.aar",
          "url": "wemeet-3.6.203.71.aar",
          "size": 16817990,
          "sha512": "cadf1b1383b9bbaef7b62e640e4ea13dfeb2591b0750eeafa76c42bd40bf14a4b5a396d5d3f6217bf5c3966cc8aa9c2651e9f2186d456212700099e80f9f498d",
          "sha256": "d54f801b5bbd334746dd9516b8fbadf8189ac160ff02c42db7dd1c53ac28c78b",
          "sha1": "1547189ab1eb4775523b9375c75d8f96f855d29a",
          "md5": "41539d18e3628202920a334e424ab98c"
        }
      ]
    }
  ]
}
