{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet.modules",
    "module": "screen_share",
    "version": "3.12.201.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "screen_share-3.12.201.9.aar",
          "url": "screen_share-3.12.201.9.aar",
          "size": 1886785,
          "sha512": "682d1b9ba0821bb46cc68f000ff105bbb90d07f7056652d6f1d192f2b7f5de40f95b5ed19719dc8c33b1da300fff66607b9a26680ad7ad89739c1d1a4c0f088a",
          "sha256": "b9890d22d189ddb9f20112695cae4ab438bfe5396a85d22148af11324ee2ea5f",
          "sha1": "0b562f1e6d2131eac3727a9a2f102d380ce7964f",
          "md5": "07fdc9bd50bba1fd112c23faa89e24b4"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webcore",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "professional",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "whiteboard",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "xcast",
          "version": {
            "requires": "3.12.201.9"
          }
        }
      ],
      "files": [
        {
          "name": "screen_share-3.12.201.9.aar",
          "url": "screen_share-3.12.201.9.aar",
          "size": 1886785,
          "sha512": "682d1b9ba0821bb46cc68f000ff105bbb90d07f7056652d6f1d192f2b7f5de40f95b5ed19719dc8c33b1da300fff66607b9a26680ad7ad89739c1d1a4c0f088a",
          "sha256": "b9890d22d189ddb9f20112695cae4ab438bfe5396a85d22148af11324ee2ea5f",
          "sha1": "0b562f1e6d2131eac3727a9a2f102d380ce7964f",
          "md5": "07fdc9bd50bba1fd112c23faa89e24b4"
        }
      ]
    }
  ]
}
