{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "quick_meeting",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "quick_meeting-3.6.200.23.aar",
          "url": "quick_meeting-3.6.200.23.aar",
          "size": 200384,
          "sha512": "6f54759d15f8bb6a0903d9b34c099067fa9c3824e318856d5e31200f9b251c578a2f0792ebba6fce6d39133165cb7fd78b78c8c82e9b1f88ece5fbad0ced0d57",
          "sha256": "ae7d385e09653253b1838c9b0b7fce2811d2c007adc035032c4e86de92a536c0",
          "sha1": "befa4197cc004936d6813cd0c0800855339978d9",
          "md5": "e264990bb7e3244f86d3a4ab4645cfe7"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "quick_meeting-3.6.200.23.aar",
          "url": "quick_meeting-3.6.200.23.aar",
          "size": 200384,
          "sha512": "6f54759d15f8bb6a0903d9b34c099067fa9c3824e318856d5e31200f9b251c578a2f0792ebba6fce6d39133165cb7fd78b78c8c82e9b1f88ece5fbad0ced0d57",
          "sha256": "ae7d385e09653253b1838c9b0b7fce2811d2c007adc035032c4e86de92a536c0",
          "sha1": "befa4197cc004936d6813cd0c0800855339978d9",
          "md5": "e264990bb7e3244f86d3a4ab4645cfe7"
        }
      ]
    }
  ]
}
