{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "wmp",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "base-jni",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "wmp-3.6.200.23.aar",
          "url": "wmp-3.6.200.23.aar",
          "size": 39783806,
          "sha512": "2130d727f0b994f8f78c9981d84baa7f1a436913959b415c97891bd56404810b4ee884889335c6e3a56ddea3a3167d1d5d2718ae1a5def71aa98d7c266df6b12",
          "sha256": "68afe597746c996f944f28087d404865ab4a6e9da42995812c44670004385715",
          "sha1": "7b57967531c4e4d7cd5a69a6f091dd839d82dbe1",
          "md5": "f2ebd2f83da7e9081e415b8215fe4724"
        }
      ]
    },
    {
      "name": "productReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "base-jni",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "wmp-3.6.200.23.aar",
          "url": "wmp-3.6.200.23.aar",
          "size": 39783806,
          "sha512": "2130d727f0b994f8f78c9981d84baa7f1a436913959b415c97891bd56404810b4ee884889335c6e3a56ddea3a3167d1d5d2718ae1a5def71aa98d7c266df6b12",
          "sha256": "68afe597746c996f944f28087d404865ab4a6e9da42995812c44670004385715",
          "sha1": "7b57967531c4e4d7cd5a69a6f091dd839d82dbe1",
          "md5": "f2ebd2f83da7e9081e415b8215fe4724"
        }
      ]
    }
  ]
}
