{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "module-core",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "xcast",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "auth",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "uikit",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "lottie",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "push",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "tbssdk-dynamic",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.yqritc",
          "module": "recyclerview-flexibledivider",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "module-core-3.6.200.23.aar",
          "url": "module-core-3.6.200.23.aar",
          "size": 3269305,
          "sha512": "78a31cad143e2d5499a7d4e1622db7e622b945a1b4273b1b574464ad5e2b351e564c3ffef8a1db2bb6a8091c16ac0015fa11de394568d4aff7345968c6aa0f47",
          "sha256": "a7d4f30069db923cd1ce585ebdf16b82fe6dd910ddc6862f233e1b5881999960",
          "sha1": "0cc668c8a221bc79cfc4540a96f44f8d1afefbfa",
          "md5": "986ccf073258adf7cab376772f43fe4c"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "xcast",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "auth",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "uikit",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "lottie",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "push",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "tbssdk-dynamic",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.yqritc",
          "module": "recyclerview-flexibledivider",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "captchasdk",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-loader",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.31"
          }
        },
        {
          "group": "yt-parvati.yt-parvati-wemeet",
          "module": "yt-parvati-wemeet-resource",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "yt-parvati.yt-parvati-wemeet",
          "module": "yt-parvati-wemeet-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "yt-3d-avatar.wemeet",
          "module": "yt-3d-avatar-wemeet",
          "version": {
            "requires": "v2.2.12"
          }
        },
        {
          "group": "youtu.yt-mobile-sdk",
          "module": "libYTCommon",
          "version": {
            "requires": "v2.4.4_meeting"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-core-3.6.200.23.aar",
          "url": "module-core-3.6.200.23.aar",
          "size": 3269305,
          "sha512": "78a31cad143e2d5499a7d4e1622db7e622b945a1b4273b1b574464ad5e2b351e564c3ffef8a1db2bb6a8091c16ac0015fa11de394568d4aff7345968c6aa0f47",
          "sha256": "a7d4f30069db923cd1ce585ebdf16b82fe6dd910ddc6862f233e1b5881999960",
          "sha1": "0cc668c8a221bc79cfc4540a96f44f8d1afefbfa",
          "md5": "986ccf073258adf7cab376772f43fe4c"
        }
      ]
    }
  ]
}
