{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet.modules",
    "module": "settings",
    "version": "3.12.201.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "videoplayer",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "settings-3.12.201.9.aar",
          "url": "settings-3.12.201.9.aar",
          "size": 2123607,
          "sha512": "7445c66010337edd163ab0ad6af9b69a57a322a451b43ce2088bcca935bfe098d74064be532f969553b5e0a1341c4a20d847851d71877f6d390855400390aff4",
          "sha256": "bd4d448153768900ee3cf578043fe00fdcd4315c60d796d8c1682f93b41a4798",
          "sha1": "ad97d0ad8d58051fe8669edff2f076e80a3f3115",
          "md5": "a1a61091c19239470601d61d9c1286fa"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "videoplayer",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webcore",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "professional",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "settings-3.12.201.9.aar",
          "url": "settings-3.12.201.9.aar",
          "size": 2123607,
          "sha512": "7445c66010337edd163ab0ad6af9b69a57a322a451b43ce2088bcca935bfe098d74064be532f969553b5e0a1341c4a20d847851d71877f6d390855400390aff4",
          "sha256": "bd4d448153768900ee3cf578043fe00fdcd4315c60d796d8c1682f93b41a4798",
          "sha1": "ad97d0ad8d58051fe8669edff2f076e80a3f3115",
          "md5": "a1a61091c19239470601d61d9c1286fa"
        }
      ]
    }
  ]
}
