{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "push",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "push-3.6.200.23.aar",
          "url": "push-3.6.200.23.aar",
          "size": 65855,
          "sha512": "ac16be8786afaee3d9c903ad15ddaf6df77627a1ee9becadc9c0a706fda22032b80001d0136303b6285a0431fda87cd02e0eb8ad1b7b43fdc86de5f4b9fba175",
          "sha256": "399eec794bf81179c1cb1a90e2304d5f25e771b21e84e127f7782841d5f6e3bc",
          "sha1": "5a9e50b095e0fcbb456e92ab575fa94f001ec92d",
          "md5": "c46810989add0a4353154be18d9742fd"
        }
      ]
    },
    {
      "name": "productReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "push-3.6.200.23.aar",
          "url": "push-3.6.200.23.aar",
          "size": 65855,
          "sha512": "ac16be8786afaee3d9c903ad15ddaf6df77627a1ee9becadc9c0a706fda22032b80001d0136303b6285a0431fda87cd02e0eb8ad1b7b43fdc86de5f4b9fba175",
          "sha256": "399eec794bf81179c1cb1a90e2304d5f25e771b21e84e127f7782841d5f6e3bc",
          "sha1": "5a9e50b095e0fcbb456e92ab575fa94f001ec92d",
          "md5": "c46810989add0a4353154be18d9742fd"
        }
      ]
    }
  ]
}
