{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "tm-bugly-sdk",
    "version": "3.6.203.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet",
          "version": {
            "requires": "3.6.203.71"
          }
        }
      ],
      "files": [
        {
          "name": "tm-bugly-sdk-3.6.203.71.aar",
          "url": "tm-bugly-sdk-3.6.203.71.aar",
          "size": 57198,
          "sha512": "d2331f54b312b6449f82791ae18123741aa4d5171199093821e4fbcbff47108bd54169911b6725fb2199ea9d71529ddc9812f8ea6106a108a3690707445c1e5d",
          "sha256": "6ebe64f31f0a2051f9e49e399a6a2b5ae1da6755713813ca623d4058bf142b0c",
          "sha1": "8c2a2ee5afceff0cf06cb903f4ff6cfff3992749",
          "md5": "b63532a057254aeaf0c2ebacf9b02580"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport",
          "version": {
            "requires": "4.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "tm-bugly-sdk-3.6.203.71.aar",
          "url": "tm-bugly-sdk-3.6.203.71.aar",
          "size": 57198,
          "sha512": "d2331f54b312b6449f82791ae18123741aa4d5171199093821e4fbcbff47108bd54169911b6725fb2199ea9d71529ddc9812f8ea6106a108a3690707445c1e5d",
          "sha256": "6ebe64f31f0a2051f9e49e399a6a2b5ae1da6755713813ca623d4058bf142b0c",
          "sha1": "8c2a2ee5afceff0cf06cb903f4ff6cfff3992749",
          "md5": "b63532a057254aeaf0c2ebacf9b02580"
        }
      ]
    }
  ]
}
