{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "web_share",
    "version": "3.6.203.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "web_share-3.6.203.71.aar",
          "url": "web_share-3.6.203.71.aar",
          "size": 321163,
          "sha512": "b365bdcee5cc9e7436c2047ff5dc26360cba671480870555abe6692455e9fa7687c2ea3614c6944f4344a6e8154901ba7228c3875da3122c11a9cd0ad05f11b1",
          "sha256": "53d4dea441e253e49672db059e90262bdc3b87d0a6b1562650ae01fbcfac306f",
          "sha1": "c563fa8a58265c3a3f57fe39235944e1618109d2",
          "md5": "45eb4f1649e454180a8112f00e8c7029"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.203.71"
          }
        }
      ],
      "files": [
        {
          "name": "web_share-3.6.203.71.aar",
          "url": "web_share-3.6.203.71.aar",
          "size": 321163,
          "sha512": "b365bdcee5cc9e7436c2047ff5dc26360cba671480870555abe6692455e9fa7687c2ea3614c6944f4344a6e8154901ba7228c3875da3122c11a9cd0ad05f11b1",
          "sha256": "53d4dea441e253e49672db059e90262bdc3b87d0a6b1562650ae01fbcfac306f",
          "sha1": "c563fa8a58265c3a3f57fe39235944e1618109d2",
          "md5": "45eb4f1649e454180a8112f00e8c7029"
        }
      ]
    }
  ]
}
