{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "warmup_media",
    "version": "3.6.203.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "warmup_media-3.6.203.71.aar",
          "url": "warmup_media-3.6.203.71.aar",
          "size": 448159,
          "sha512": "7ba093791db5b1b42706b75a21b1ee1995925d6433aff3efbcba0e845c7e21680284f3d2de54fd7c2d6e135e2b5e49668118f109db62ccf2a7b2838a0473dc74",
          "sha256": "7e90aa7c09903a833211014ab30857952fa9b33dad23fefa5466867f39a7173a",
          "sha1": "3fec19ccc550a3c0bbe2789c383c39f5b2d0d5b2",
          "md5": "fd8d99ecec71e933baecc808aa127f1b"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.liteav",
          "module": "LiteAVSDK_Player",
          "version": {
            "requires": "9.3.10769"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "warmup_media-3.6.203.71.aar",
          "url": "warmup_media-3.6.203.71.aar",
          "size": 448159,
          "sha512": "7ba093791db5b1b42706b75a21b1ee1995925d6433aff3efbcba0e845c7e21680284f3d2de54fd7c2d6e135e2b5e49668118f109db62ccf2a7b2838a0473dc74",
          "sha256": "7e90aa7c09903a833211014ab30857952fa9b33dad23fefa5466867f39a7173a",
          "sha1": "3fec19ccc550a3c0bbe2789c383c39f5b2d0d5b2",
          "md5": "fd8d99ecec71e933baecc808aa127f1b"
        }
      ]
    }
  ]
}
