{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "docs",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "docs-3.6.200.23.aar",
          "url": "docs-3.6.200.23.aar",
          "size": 363881,
          "sha512": "e4571a637bfcb279020b7931960869d32888ede4b9e5080bc5fd7a3d219c2d20b83f0caed8430eb3fe3f73890e33cf970de7039e8b46c18c90c6fd9c1f68515e",
          "sha256": "4182666495d9f26249329d57b18ea4c7e06b873a4d9419512be0fee47c887a64",
          "sha1": "37ac22e467953e9e4c6718140c8b2ed828509b14",
          "md5": "b6f4dcdb99f6161ff50c3fa382c306ed"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "docs-3.6.200.23.aar",
          "url": "docs-3.6.200.23.aar",
          "size": 363881,
          "sha512": "e4571a637bfcb279020b7931960869d32888ede4b9e5080bc5fd7a3d219c2d20b83f0caed8430eb3fe3f73890e33cf970de7039e8b46c18c90c6fd9c1f68515e",
          "sha256": "4182666495d9f26249329d57b18ea4c7e06b873a4d9419512be0fee47c887a64",
          "sha1": "37ac22e467953e9e4c6718140c8b2ed828509b14",
          "md5": "b6f4dcdb99f6161ff50c3fa382c306ed"
        }
      ]
    }
  ]
}
