{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "kt-extensions",
    "version": "3.6.203.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kt-extensions-3.6.203.71.aar",
          "url": "kt-extensions-3.6.203.71.aar",
          "size": 57820,
          "sha512": "e3c5d8db9a3e86c1fe96a5553c14fc55a8ca6561e4ef1bb99fe82870652a076b7a6adab446ed85c61eb27a692d6299d98f9d78a0fa396f017e431e104e6e2e8d",
          "sha256": "e1f24f9438b8e6264c10ccafcf1697c00eae807bc883cd371b882a090a267ee0",
          "sha1": "252bd9683f7271783dcac56d9ebc10d00286db6e",
          "md5": "7b1bc9de55e87be0f99c944fdd76994e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "kt-extensions-3.6.203.71.aar",
          "url": "kt-extensions-3.6.203.71.aar",
          "size": 57820,
          "sha512": "e3c5d8db9a3e86c1fe96a5553c14fc55a8ca6561e4ef1bb99fe82870652a076b7a6adab446ed85c61eb27a692d6299d98f9d78a0fa396f017e431e104e6e2e8d",
          "sha256": "e1f24f9438b8e6264c10ccafcf1697c00eae807bc883cd371b882a090a267ee0",
          "sha1": "252bd9683f7271783dcac56d9ebc10d00286db6e",
          "md5": "7b1bc9de55e87be0f99c944fdd76994e"
        }
      ]
    }
  ]
}
