{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "account",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "account-3.6.200.23.aar",
          "url": "account-3.6.200.23.aar",
          "size": 890931,
          "sha512": "84ca86fb650609c78916ab940f9249f1cc6d68cfa77276eedb7c39bc27aad98ffd01027adaa7c00c8828496beabbf2326d60d5f6872bb46f5b34d660dca62bc4",
          "sha256": "7c3761165a9b15b72ccec8d122504d56feef01badbd616236248ca314225554f",
          "sha1": "19e02436956ff447ce979f8eb30d001124e5ea8d",
          "md5": "6234e4706f9fa7d63decc109d30b59ea"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "account-3.6.200.23.aar",
          "url": "account-3.6.200.23.aar",
          "size": 890931,
          "sha512": "84ca86fb650609c78916ab940f9249f1cc6d68cfa77276eedb7c39bc27aad98ffd01027adaa7c00c8828496beabbf2326d60d5f6872bb46f5b34d660dca62bc4",
          "sha256": "7c3761165a9b15b72ccec8d122504d56feef01badbd616236248ca314225554f",
          "sha1": "19e02436956ff447ce979f8eb30d001124e5ea8d",
          "md5": "6234e4706f9fa7d63decc109d30b59ea"
        }
      ]
    }
  ]
}
