{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "schedule_meeting",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "schedule_meeting-3.6.200.23.aar",
          "url": "schedule_meeting-3.6.200.23.aar",
          "size": 1086923,
          "sha512": "a23edbc0b9446a952bf22ae94d06f093ae758506bd40be1b8cbb28168d3023f18b087cf219f3d31f97a1f7028d165160e322a6ca6fdcbe7604750cbbcba2a37c",
          "sha256": "6b6703b32d587451d11816d2695c6e96654b7b1d9e3c3a69790b2993e11b8521",
          "sha1": "a0b6f28f7eb05887589bd157495f7f1ab6211f94",
          "md5": "c1f89a1ee2de26730fffef7ca8b67873"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "schedule_meeting-3.6.200.23.aar",
          "url": "schedule_meeting-3.6.200.23.aar",
          "size": 1086923,
          "sha512": "a23edbc0b9446a952bf22ae94d06f093ae758506bd40be1b8cbb28168d3023f18b087cf219f3d31f97a1f7028d165160e322a6ca6fdcbe7604750cbbcba2a37c",
          "sha256": "6b6703b32d587451d11816d2695c6e96654b7b1d9e3c3a69790b2993e11b8521",
          "sha1": "a0b6f28f7eb05887589bd157495f7f1ab6211f94",
          "md5": "c1f89a1ee2de26730fffef7ca8b67873"
        }
      ]
    }
  ]
}
