{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "videoplayer",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.liteav",
          "module": "LiteAVSDK_Player",
          "version": {
            "requires": "9.3.10769"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "videoplayer-3.6.200.23.aar",
          "url": "videoplayer-3.6.200.23.aar",
          "size": 105395,
          "sha512": "c09176865e25831c41590b0225dae8e9964792e5df133ed3f8a952bcd63c74a44c7cd0f3ff29ac5dd5d7785df79bf6c7cae2afd221473def4174dd953b5a2eb9",
          "sha256": "187d73cf2648dbfaeed01f45c5903df6374083d7ff16ffda87986e9a5ff6d096",
          "sha1": "cd54ba875d0b3e48690db34d26e66e5a80e711ad",
          "md5": "100953cb5466290f9987d7ad7f17f3aa"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.liteav",
          "module": "LiteAVSDK_Player",
          "version": {
            "requires": "9.3.10769"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "videoplayer-3.6.200.23.aar",
          "url": "videoplayer-3.6.200.23.aar",
          "size": 105395,
          "sha512": "c09176865e25831c41590b0225dae8e9964792e5df133ed3f8a952bcd63c74a44c7cd0f3ff29ac5dd5d7785df79bf6c7cae2afd221473def4174dd953b5a2eb9",
          "sha256": "187d73cf2648dbfaeed01f45c5903df6374083d7ff16ffda87986e9a5ff6d096",
          "sha1": "cd54ba875d0b3e48690db34d26e66e5a80e711ad",
          "md5": "100953cb5466290f9987d7ad7f17f3aa"
        }
      ]
    }
  ]
}
