{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "tm-android-sdk",
    "version": "3.12.201.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "tm-bugly-sdk",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "tm-android-sdk-3.12.201.9.aar",
          "url": "tm-android-sdk-3.12.201.9.aar",
          "size": 460252,
          "sha512": "d0c840b02aed0cbeb296bcd328a6ee769090682f745a4413cd457e1489565b75f312372156bfb4c8dcaf2d1f4c69b615b82d41a73fbad9b608b2a9e80c114c61",
          "sha256": "053941b71d55c25005d9d4b935db8b45a7d4d13b333ac4ebf08b559927bc9f0c",
          "sha1": "a67b43c3dae0e3f6f02ae526d14e17f83c85bddc",
          "md5": "4025c6fef98f162d8938d83cd69c10a0"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "tm-bugly-sdk",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "account",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "activity_space",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "appbox",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "ar_avatar",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "audio",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "breakout_room",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "calendar",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "caption",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "chat",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "company_contacts",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "docs",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "gift",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "handsup",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "historical_meetings",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "idea",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "invite",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "join_meeting",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "login",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "media_process",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "meeting_live",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "meeting_room",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "member",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "misc",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "proxy",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "question_answer",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "quick_meeting",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "record",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "rest",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "ring",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "safety",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "schedule_meeting",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "screen_share",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "settings",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "sim_interpret",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "tm_sdk",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "video",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "vote",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "warmup_media",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet.modules",
          "module": "web_share",
          "version": {
            "requires": "3.12.201.9"
          }
        }
      ],
      "files": [
        {
          "name": "tm-android-sdk-3.12.201.9.aar",
          "url": "tm-android-sdk-3.12.201.9.aar",
          "size": 460252,
          "sha512": "d0c840b02aed0cbeb296bcd328a6ee769090682f745a4413cd457e1489565b75f312372156bfb4c8dcaf2d1f4c69b615b82d41a73fbad9b608b2a9e80c114c61",
          "sha256": "053941b71d55c25005d9d4b935db8b45a7d4d13b333ac4ebf08b559927bc9f0c",
          "sha1": "a67b43c3dae0e3f6f02ae526d14e17f83c85bddc",
          "md5": "4025c6fef98f162d8938d83cd69c10a0"
        }
      ]
    }
  ]
}
