{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet.modules",
    "module": "settings",
    "version": "3.12.401.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "videoplayer",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "settings-3.12.401.11.aar",
          "url": "settings-3.12.401.11.aar",
          "size": 2124258,
          "sha512": "6233a3b4e8cbfc496d3da0b188891cd3a5e6cd758e07168f662ad7f2337fdabdfd505a847ab842c63d6e37ef54925e97ef88a79ca6e4accca48b7d145e152312",
          "sha256": "84bd1700df16ef044a5e4f212cc652e94bcf2d177ff10dae4b2c53112acdf25f",
          "sha1": "6a614bf4f920e03bf7f3061d1e7a755525d2c854",
          "md5": "048f98c134c9507fdeca7a049e149e2e"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "videoplayer",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webcore",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "professional",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "settings-3.12.401.11.aar",
          "url": "settings-3.12.401.11.aar",
          "size": 2124258,
          "sha512": "6233a3b4e8cbfc496d3da0b188891cd3a5e6cd758e07168f662ad7f2337fdabdfd505a847ab842c63d6e37ef54925e97ef88a79ca6e4accca48b7d145e152312",
          "sha256": "84bd1700df16ef044a5e4f212cc652e94bcf2d177ff10dae4b2c53112acdf25f",
          "sha1": "6a614bf4f920e03bf7f3061d1e7a755525d2c854",
          "md5": "048f98c134c9507fdeca7a049e149e2e"
        }
      ]
    }
  ]
}
