{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "webview",
    "version": "3.12.201.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "websdk",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "webview-3.12.201.9.aar",
          "url": "webview-3.12.201.9.aar",
          "size": 976203,
          "sha512": "79f443a0ac3764744cbc929f7970eda10ad30a9af1497ba2cad454341ae15193931e9bca2520d19f9c0be6d310d20af115b12057a0f0d69cd4acf3ea3fda4a21",
          "sha256": "1f4de9e9944f2322e8b72caedbfc6adf42c1a92157350aa719aabe58a5f53656",
          "sha1": "f902606aa3175f2bc0d29e278db530f8b7cea353",
          "md5": "6850dfdfa322232c1061ea6136a6f11a"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "websdk",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-loader",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.45"
          }
        },
        {
          "group": "com.tencent.liteav",
          "module": "LiteAVSDK_Player",
          "version": {
            "requires": "9.5.29040"
          }
        }
      ],
      "files": [
        {
          "name": "webview-3.12.201.9.aar",
          "url": "webview-3.12.201.9.aar",
          "size": 976203,
          "sha512": "79f443a0ac3764744cbc929f7970eda10ad30a9af1497ba2cad454341ae15193931e9bca2520d19f9c0be6d310d20af115b12057a0f0d69cd4acf3ea3fda4a21",
          "sha256": "1f4de9e9944f2322e8b72caedbfc6adf42c1a92157350aa719aabe58a5f53656",
          "sha1": "f902606aa3175f2bc0d29e278db530f8b7cea353",
          "md5": "6850dfdfa322232c1061ea6136a6f11a"
        }
      ]
    }
  ]
}
