{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "video",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "video-3.6.200.23.aar",
          "url": "video-3.6.200.23.aar",
          "size": 762019,
          "sha512": "266232d6205b288fa01f90df0b9bd5d07a7d8c24520b2728c8ff80e58eb8071083e23eb632e60146a0b4105e0d2c639c5e26d639f27b7c06bc50bb34c82123af",
          "sha256": "36107d8d57a9dedcbf2495bf1a17f70bb999a00d16a55ad71cbfcf3852086955",
          "sha1": "bb0f727613cb3dcfeefc140a6f5b9038e9959326",
          "md5": "532369eeb6eb82de07ca5bc0198df16a"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "video-3.6.200.23.aar",
          "url": "video-3.6.200.23.aar",
          "size": 762019,
          "sha512": "266232d6205b288fa01f90df0b9bd5d07a7d8c24520b2728c8ff80e58eb8071083e23eb632e60146a0b4105e0d2c639c5e26d639f27b7c06bc50bb34c82123af",
          "sha256": "36107d8d57a9dedcbf2495bf1a17f70bb999a00d16a55ad71cbfcf3852086955",
          "sha1": "bb0f727613cb3dcfeefc140a6f5b9038e9959326",
          "md5": "532369eeb6eb82de07ca5bc0198df16a"
        }
      ]
    }
  ]
}
