{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "wemeet-kapt",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-kapt-3.6.200.23.aar",
          "url": "wemeet-kapt-3.6.200.23.aar",
          "size": 3667,
          "sha512": "5a4cb528c83a794a79eb8f2f7838709dc3348de077817e59659f7fcfbc13c08be9f43f4cfd5f52b21954cd0cf28bd4d238f1f68bb951f9cc18b4c9b503eee7a5",
          "sha256": "198141675f64d149b4b7c2ad694abec6da330b6a2c9709f7e3adbd440ee2815d",
          "sha1": "ffb1711d1eedb9128871be1b08111c492e64cccb",
          "md5": "76d43ea26d622d2ad0be9b0423e70e05"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-kapt-3.6.200.23.aar",
          "url": "wemeet-kapt-3.6.200.23.aar",
          "size": 3667,
          "sha512": "5a4cb528c83a794a79eb8f2f7838709dc3348de077817e59659f7fcfbc13c08be9f43f4cfd5f52b21954cd0cf28bd4d238f1f68bb951f9cc18b4c9b503eee7a5",
          "sha256": "198141675f64d149b4b7c2ad694abec6da330b6a2c9709f7e3adbd440ee2815d",
          "sha1": "ffb1711d1eedb9128871be1b08111c492e64cccb",
          "md5": "76d43ea26d622d2ad0be9b0423e70e05"
        }
      ]
    }
  ]
}
