{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "schedule_meeting",
    "version": "3.6.203.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "schedule_meeting-3.6.203.71.aar",
          "url": "schedule_meeting-3.6.203.71.aar",
          "size": 1127769,
          "sha512": "0b958f133c25b5fd3965cb1abaf769c57956477747271b2a9682dfea6fed34dcf5001df834277abeb93e6f0b8598c7a7df9cae69d53ad5b1e5dd4dbec36ff1fe",
          "sha256": "18d5bf4a226a5c854285fb95715ff0fd3ad320c3ab59c0ca755fca99784da418",
          "sha1": "803a0aa3135a824d32039b914510f503e8fe5645",
          "md5": "0a00ba497251ead49854389d96eba19a"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.203.71"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "schedule_meeting-3.6.203.71.aar",
          "url": "schedule_meeting-3.6.203.71.aar",
          "size": 1127769,
          "sha512": "0b958f133c25b5fd3965cb1abaf769c57956477747271b2a9682dfea6fed34dcf5001df834277abeb93e6f0b8598c7a7df9cae69d53ad5b1e5dd4dbec36ff1fe",
          "sha256": "18d5bf4a226a5c854285fb95715ff0fd3ad320c3ab59c0ca755fca99784da418",
          "sha1": "803a0aa3135a824d32039b914510f503e8fe5645",
          "md5": "0a00ba497251ead49854389d96eba19a"
        }
      ]
    }
  ]
}
