{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "professional",
    "version": "3.12.201.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "professional-3.12.201.9.aar",
          "url": "professional-3.12.201.9.aar",
          "size": 90694,
          "sha512": "261e6935cb9476d982a9943a97ba2cb69fea7f3c0ead1499dfae787afa80c0a7d245d746e5557ed84081b79e646025863d2d8a96ea2d9a2156b87216ac76a270",
          "sha256": "b745a4f59568e386b2fb9f1d63c05654f8a440279b8fe0a1fc0aeae7d63a59c8",
          "sha1": "e8c2496a98275613a8bc2bb0a118a2971958c1a0",
          "md5": "23a31e01fcafcb982380238d91c55839"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.201.9"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.201.9"
          }
        }
      ],
      "files": [
        {
          "name": "professional-3.12.201.9.aar",
          "url": "professional-3.12.201.9.aar",
          "size": 90694,
          "sha512": "261e6935cb9476d982a9943a97ba2cb69fea7f3c0ead1499dfae787afa80c0a7d245d746e5557ed84081b79e646025863d2d8a96ea2d9a2156b87216ac76a270",
          "sha256": "b745a4f59568e386b2fb9f1d63c05654f8a440279b8fe0a1fc0aeae7d63a59c8",
          "sha1": "e8c2496a98275613a8bc2bb0a118a2971958c1a0",
          "md5": "23a31e01fcafcb982380238d91c55839"
        }
      ]
    }
  ]
}
