{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "safety",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "safety-3.6.200.23.aar",
          "url": "safety-3.6.200.23.aar",
          "size": 164774,
          "sha512": "86641ed80a33ad8c89adbd8d2249c83667280361b81726f98f5332d229e79b9d39a739d655c5a090062b2d8c232b58150e643e60423d9a4bf83c7e6b0f753e9c",
          "sha256": "5fabf1d3348d6e4e431b8896697a77b1ebda7a8c0b8d3979957d23b3c77791ca",
          "sha1": "b175d0e367091fec5f9f629ea6c847e6aeda0d5e",
          "md5": "ea1239deb24c392c37a5dd3696f06a7a"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "safety-3.6.200.23.aar",
          "url": "safety-3.6.200.23.aar",
          "size": 164774,
          "sha512": "86641ed80a33ad8c89adbd8d2249c83667280361b81726f98f5332d229e79b9d39a739d655c5a090062b2d8c232b58150e643e60423d9a4bf83c7e6b0f753e9c",
          "sha256": "5fabf1d3348d6e4e431b8896697a77b1ebda7a8c0b8d3979957d23b3c77791ca",
          "sha1": "b175d0e367091fec5f9f629ea6c847e6aeda0d5e",
          "md5": "ea1239deb24c392c37a5dd3696f06a7a"
        }
      ]
    }
  ]
}
