{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet.modules",
    "module": "schedule_meeting",
    "version": "3.12.401.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "videoplayer",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "schedule_meeting-3.12.401.11.aar",
          "url": "schedule_meeting-3.12.401.11.aar",
          "size": 2125749,
          "sha512": "c23ab9f0c5c5c364a4eee5d412eee446180903280401b2c57859e9a12458e4f513a4f004ba926d923b77223638d4f6fae6caef5f0ebab2c39688a126f75db8e9",
          "sha256": "cb1a6229981f0f3cbed551fe1665226f6a42dda07ae35f24f4a5b4f754bee171",
          "sha1": "542020f9ea4e90dff85427c0e09b6081cd49bf3b",
          "md5": "ce4c624a919722504792305ba4892722"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "videoplayer",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webcore",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "professional",
          "version": {
            "requires": "3.12.401.11"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "schedule_meeting-3.12.401.11.aar",
          "url": "schedule_meeting-3.12.401.11.aar",
          "size": 2125749,
          "sha512": "c23ab9f0c5c5c364a4eee5d412eee446180903280401b2c57859e9a12458e4f513a4f004ba926d923b77223638d4f6fae6caef5f0ebab2c39688a126f75db8e9",
          "sha256": "cb1a6229981f0f3cbed551fe1665226f6a42dda07ae35f24f4a5b4f754bee171",
          "sha1": "542020f9ea4e90dff85427c0e09b6081cd49bf3b",
          "md5": "ce4c624a919722504792305ba4892722"
        }
      ]
    }
  ]
}
