{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "ring",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ring-3.6.200.23.aar",
          "url": "ring-3.6.200.23.aar",
          "size": 155670,
          "sha512": "f9055a466332f7221984a2e146484495a70f572465465af19b73b0d95fb89b94c72e70b150598269774c8f5f399b1b64290b2b367030fa5a625786540c7e48f7",
          "sha256": "ab9b185db43604e7487c6b39e095901af5e3f056d4cfdba4fde2554785e0d9f5",
          "sha1": "168a7a7daa67a3f743629ad36e08ef0fb077351b",
          "md5": "b95bec75b0fd1ce3c44a35cb75d728a7"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "ring-3.6.200.23.aar",
          "url": "ring-3.6.200.23.aar",
          "size": 155670,
          "sha512": "f9055a466332f7221984a2e146484495a70f572465465af19b73b0d95fb89b94c72e70b150598269774c8f5f399b1b64290b2b367030fa5a625786540c7e48f7",
          "sha256": "ab9b185db43604e7487c6b39e095901af5e3f056d4cfdba4fde2554785e0d9f5",
          "sha1": "168a7a7daa67a3f743629ad36e08ef0fb077351b",
          "md5": "b95bec75b0fd1ce3c44a35cb75d728a7"
        }
      ]
    }
  ]
}
