{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "gift",
    "version": "3.6.200.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t3bm6tcf2behrocdhqjvvr2fra"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "gift-3.6.200.23.aar",
          "url": "gift-3.6.200.23.aar",
          "size": 183881,
          "sha512": "63030e2b649811b1ec308bc467528dd06d1a9dd3ff3574114b0b9c8bb88b9598ecd00d14e91d0b878943de5dbe1e8e92205031391dc16001dc802832ec5fca2e",
          "sha256": "b8352ef3f674626a381a69c645a28e99e1182d4867af12e472aa0d1b6c07bb52",
          "sha1": "a2fd130727cda08818f1abef50847f44ccfebdc2",
          "md5": "01a5200189d7bf8493c1593a365731cd"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.200.23"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.200.23"
          }
        }
      ],
      "files": [
        {
          "name": "gift-3.6.200.23.aar",
          "url": "gift-3.6.200.23.aar",
          "size": 183881,
          "sha512": "63030e2b649811b1ec308bc467528dd06d1a9dd3ff3574114b0b9c8bb88b9598ecd00d14e91d0b878943de5dbe1e8e92205031391dc16001dc802832ec5fca2e",
          "sha256": "b8352ef3f674626a381a69c645a28e99e1182d4867af12e472aa0d1b6c07bb52",
          "sha1": "a2fd130727cda08818f1abef50847f44ccfebdc2",
          "md5": "01a5200189d7bf8493c1593a365731cd"
        }
      ]
    }
  ]
}
